esphome:
  name: bath_temp
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password
#   power_save_mode: light
  # manual_ip:
  #   static_ip: 192.168.86.21
  #   gateway: 192.168.86.1  
  #   subnet: 255.255.255.0

# deep_sleep:
#   run_duration: 10s
#   sleep_duration: 30s

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

mqtt:
  broker: 192.168.86.38
  username: !secret mqtt_username
  password: !secret mqtt_password
  # client_id: esphome
  port: 1883

i2c:
  sda: 21
  scl: 22
  scan: False

# Example configuration entry
sensor:
  - platform: bmp280
    temperature:
      name: "Bath Temperature"
      oversampling: 16x
    pressure:
      name: "Bath Pressure"
    address: 0x76
    update_interval: 60s
  - platform: uptime
    name: Bath Temp Uptime Sensor