esphomeyaml:
  name: kitchen_temp
  platform: ESP32
  board: esp-wrover-kit
  includes:
    - sw420.h

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password
  # manual_ip:
  #   static_ip: 192.168.86.250
  #   gateway: 192.168.86.1  
  #   subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password
  
mqtt:
  broker: 192.168.86.38
  username: !secret mqtt_username
  password: !secret mqtt_password
  # client_id: esphome
  port: 1883

i2c:
  sda: 21
  scl: 22
  scan: False

# Example configuration entry
sensor:
  - platform: bmp280
    temperature:
      name: "kitchen Temperature"
      oversampling: 16x
    pressure:
      name: "kitchen Pressure"
    address: 0x76
    update_interval: 60s
  - platform: custom
    lambda: |-
      auto my_sensor = new MySW420Sensor();
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      name: "My Custom SW420 Sensor"    