esphome:
  name: unassigned_sonoff_switch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

mqtt:
  broker: 192.168.86.38
  username: !secret mqtt_username
  password: !secret mqtt_password
  # client_id: esphome
  port: 1883


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Unassigned Sonoff Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Unassigned Sonoff Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes